// xmms_playback_seek_mode_t
xmmsclient.XMMS_PLAYBACK_SEEK_CUR = 1;
xmmsclient.XMMS_PLAYBACK_SEEK_SET = 2;

// xmmsv_coll_type_t
xmmsclient.XMMS_COLLECTION_TYPE_REFERENCE = 0;
xmmsclient.XMMS_COLLECTION_TYPE_UNIVERSE = 1;
xmmsclient.XMMS_COLLECTION_TYPE_UNION = 2;
xmmsclient.XMMS_COLLECTION_TYPE_INTERSECTION = 3;
xmmsclient.XMMS_COLLECTION_TYPE_COMPLEMENT = 4;
xmmsclient.XMMS_COLLECTION_TYPE_HAS = 5;
xmmsclient.XMMS_COLLECTION_TYPE_MATCH = 6;
xmmsclient.XMMS_COLLECTION_TYPE_TOKEN = 7;
xmmsclient.XMMS_COLLECTION_TYPE_EQUALS = 8;
xmmsclient.XMMS_COLLECTION_TYPE_NOTEQUAL = 9;
xmmsclient.XMMS_COLLECTION_TYPE_SMALLER = 10;
xmmsclient.XMMS_COLLECTION_TYPE_SMALLEREQ = 11;
xmmsclient.XMMS_COLLECTION_TYPE_GREATER = 12;
xmmsclient.XMMS_COLLECTION_TYPE_GREATEREQ = 13;
xmmsclient.XMMS_COLLECTION_TYPE_ORDER = 14;
xmmsclient.XMMS_COLLECTION_TYPE_LIMIT = 15;
xmmsclient.XMMS_COLLECTION_TYPE_MEDIASET = 16;
xmmsclient.XMMS_COLLECTION_TYPE_IDLIST = 17;

// xmms_playback_status_t
xmmsclient.XMMS_PLAYBACK_STATUS_STOP = 0;
xmmsclient.XMMS_PLAYBACK_STATUS_PLAY = 1;
xmmsclient.XMMS_PLAYBACK_STATUS_PAUSE = 2;

// xmms_playlist_changed_actions_t
xmmsclient.XMMS_PLAYLIST_CHANGED_ADD = 0;
xmmsclient.XMMS_PLAYLIST_CHANGED_INSERT = 1;
xmmsclient.XMMS_PLAYLIST_CHANGED_SHUFFLE = 2;
xmmsclient.XMMS_PLAYLIST_CHANGED_REMOVE = 3;
xmmsclient.XMMS_PLAYLIST_CHANGED_CLEAR = 4;
xmmsclient.XMMS_PLAYLIST_CHANGED_MOVE = 5;
xmmsclient.XMMS_PLAYLIST_CHANGED_SORT = 6;
xmmsclient.XMMS_PLAYLIST_CHANGED_UPDATE = 7;
xmmsclient.XMMS_PLAYLIST_CHANGED_REPLACE = 8;

